[package]
name = "sch"
version = "0.1.0"
authors = ["wolfgang <wolfgang@wolfgangdeutsch.work>"]
edition = "2018"

[dev-dependencies]

[dependencies]
rand = "0.6.4"
console = "0.7.5"
regex = "1"
raylib = "0.9"